name: Test with Ruby head

on:
  schedule:
    - cron: '11 14 * * 0'
  workflow_dispatch:

permissions: read-all

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        ruby-version: ['head']

    name: Ruby ${{ matrix.ruby-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Set up Ruby
        uses: ruby/setup-ruby@f321cf5a4d1533575411f8752cf25b86478b0442 # v1.193.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install addons
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get install libgmp3-dev libcap-ng-dev
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake test TESTOPTS="-v --no-show-detail-immediately"
